# Mijia button automations

# Turn off workshop light
- alias: Mijia Button Long Click
  trigger:
    platform: state
    entity_id: sensor.0x00158d000122cc7a_click
    to: long
  action:
    - service: light.turn_off
      entity_id: light.0x00158d0005433223_light

# Toggle Alarm System
- alias: Mijia Button Click
  trigger:
    platform: state
    entity_id: sensor.0x00158d000122cc7a_click
    to: single
  action:
    service: >
      {% if is_state('alarm_control_panel.house_alarm', 'disarmed') %}
        alarm_control_panel.alarm_arm_home
      {% else %}
        alarm_control_panel.alarm_disarm
      {% endif %}
    data:
      entity_id: alarm_control_panel.house_alarm
      code: !secret house_alarm_code

#  Toggle indicators on double click
# - alias: Bedroom Button Double Click
#   trigger:
#     platform: state
#     entity_id: sensor.0x00158d000122cc7a_click
#     to: double
#   action:
#     - service: switch.toggle
#       entity_id: 
#         - switch.bedroom_indicator
#         - switch.kids_indicator
