# Mijia button automations

# Toggle Alarm System
- alias: Mijia Button Click
  trigger:
    platform: state
    entity_id: sensor.mijia_button_action
    to: single
  action:
    service: >
      {% if is_state('alarm_control_panel.house_alarm', 'disarmed') %}
        alarm_control_panel.alarm_arm_home
      {% else %}
        alarm_control_panel.alarm_disarm
      {% endif %}
    data:
      entity_id: alarm_control_panel.house_alarm
      code: !secret house_alarm_code

# Toggle Recuperators
- alias: ZB Remote Button 1 
  trigger:
    platform: state
    entity_id: sensor.zb_remote_action
    to: 1_single
  action:
    service: switch.toggle
    entity_id: switch.bedroom_fan

- alias: ZB Remote Button 2
  trigger:
    platform: state
    entity_id: sensor.zb_remote_action
    to: 2_single
  action:
    service: switch.toggle
    entity_id: switch.kids_fan
