- alias: Morning - lights off
  trigger:
    - event: sunrise
      offset: 0:30
      platform: sun
  action:
    service: light.turn_off
    entity_id:
      - light.upstairs
      - light.downstairs
      - light.basement

- alias: Evening - lights on
  trigger:
    - event: sunset
      offset: -0:30
      platform: sun
  action:
  - service: light.turn_on
    entity_id: light.upstairs

- alias: Turn off upstairs on sleep time
  trigger:
    - platform: time
      at: "21:40:00"
  action:
    - service: light.turn_off
      entity_id: light.upstairs

- alias: Restore upstairs light after sleep time
  trigger:
    - platform: time
      at: "22:20:00"
  action:
    - service: light.turn_on
      entity_id: light.upstairs

# Downstairs movement light
- alias: Downstairs motion on
  trigger:
    platform: state
    entity_id: group.downstairs_motion
    from: 'off'
    to: 'on'
  condition:
    condition: numeric_state
    entity_id: sensor.0x00158d000421ccd1_illuminance
    below: 50
  action:
    - service: light.turn_on
      entity_id:
        - light.downstairs
        - light.basement
- alias: Downstairs motion off
  trigger:
    platform: state
    entity_id: group.downstairs_motion
    from: 'on'
    to: 'off'
    for:
      minutes: 2
  action:
    - service: light.turn_off
      entity_id:
        - light.basement
        - light.downstairs
