- alias: Vacuum Charging
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.bw7_power
    above: 10
    for: '00:1:00'
  condition:
    condition: state
    entity_id: automation.vacuum_charged
    state: 'off'
  action:
    - service: notify.telegram_group
      data_template:
        message: 'Philips Vacuum is charging'
    - service: automation.turn_on
      entity_id: automation.vacuum_charged

- alias: Washing Started
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.plug_158d00039fcce4_power
    above: 100
    for: '00:05:00'
  condition:
    condition: state
    entity_id: automation.vacuum_charged
    state: 'off'
  # condition:
  #   condition: time
  #   after: '8:00:00'
  #   before: '22:00:00'
  action:
    - service: notify.telegram_group
      data_template:
        message: 'Washing Started'
    - service: automation.turn_on
      entity_id: automation.washing_finished

# Saving on water heaters
- alias: Kids Water Heater On
  trigger:
    - platform: time
      at: "03:00:00"
  action:
    - service: switch.turn_on
      entity_id: switch.bw2_switch
- alias: Kids Water Heater Off
  trigger:
    - platform: time
      at: "06:00:00"
  action:
    - service: switch.turn_off
      entity_id: switch.bw2_switch

# - alias: Bedroom Water Heater On
#   trigger:
#     - platform: time
#       at: "00:00:00"
#   action:
#     - service: switch.turn_on
#       entity_id: switch.bw1_switch
# - alias: Bedroom Water Heater Off
#   trigger:
#     - platform: time
#       at: "03:00:00"
#   action:
#     - service: switch.turn_off
#       entity_id: switch.bw1_switch

# Turn on heaters on Sunday for bath
- alias: Turn on Kids Heater on Sunday for 2h
  trigger:
    - platform: time
      at: "15:00:00"
  condition:
    condition: time
    weekday:
      - sun
  action:
    - service: switch.turn_on
      entity_id: switch.bw2_switch
    - delay: 2h
    - service: switch.turn_off
      entity_id: switch.bw2_switch
# - alias: Turn on Bedroom Heater on Sunday
#   trigger:
#     - platform: time
#       at: "16:30:00"
#   condition:
#     condition: time
#     weekday:
#       - sun
#   action:
#     - service: switch.turn_on
#       entity_id: switch.bw1_switch

# Enable Xiaomi plugs that should stay on
- alias: WiFi Repeater should stay on
  trigger:
    platform: state
    entity_id: switch.0x00158d000391fadc_switch
    to: 'off'
    for: '00:00:30'
  action:
    - service: switch.turn_on
      entity_id: switch.0x00158d000391fadc_switch

- alias: Office plug should stay on
  trigger:
    platform: state
    entity_id: switch.0x00158d00039c1bc3_switch
    to: 'off'
    for: '00:00:30'
  action:
    - service: switch.turn_on
      entity_id: switch.0x00158d00039c1bc3_switch

# Turn off dehumidifier when it's not working (full)
- alias: Full dehumidifier off
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.bw5_power
    below: 10
    for: '00:00:10' # 10s
  condition: 
    - condition: state
      entity_id: switch.bw5_switch
      state: 'on'
      for: '00:10:00' # was working at least 10m
  action:
    - service: switch.turn_off
      entity_id: switch.bw5_switch
