# Telegram notifications
# - alias: Locks notification to telegram
#   trigger:
#     platform: state
#     entity_id: 
#       - binary_sensor.door_window_sensor_158d0003d481a6
#       - binary_sensor.door_window_sensor_158d0003d4a2b2
#   action:
#     service: notify.telegram_group
#     data_template:
#       message: "{{ trigger.to_state.attributes.friendly_name }} is now *{% if trigger.to_state.state == 'off' %}closed{% else %}open{% endif %}*"

- alias: Cookoo Chime
  trigger:
    platform: time_pattern
    minutes: 0
  condition:
    condition: time
    after: '8:00:00'
    before: '22:00:00'
  action:
    service: notify.telegram_tiger
    data_template:
      message: "*{{ now().hour }}:00*"

- alias: Vacuum Charged
#  id: vacuum_charged
  trigger:
    platform: numeric_state
    entity_id: sensor.bw7_power
    below: 10
    for: '00:05:00'
  # condition:
  #   condition: time
  #   after: '8:00:00'
  #   before: '22:00:00'
  action:
    - service: notify.telegram_group
      data_template:
        message: 'Philips Vacuum is fully charged'
    - service: switch.turn_off
      entity_id: switch.bw7_switch
    - service: automation.turn_off
      entity_id: automation.vacuum_charged

- alias: Washing Finished
#  id: washing_finished
  trigger:
    platform: numeric_state
    entity_id: sensor.plug_158d00039fcce4_power
    below: 10
    for: '00:05:00'
  # condition:
  #   condition: time
  #   after: '8:00:00'
  #   before: '22:00:00'
  action:
    - service: notify.telegram_group
      data_template:
        message: 'Washing finished'
    - service: automation.turn_off
      entity_id: automation.washing_finished

- alias: Water Leak
  trigger:
    platform: state
    entity_id:
      - binary_sensor.0x00158d000405cec1_water_leak # Guest bathroom
      - binary_sensor.0x00158d00041f6a7a_water_leak # Basement
      - binary_sensor.0x00158d000484bffb_water_leak # Bathroom
      - binary_sensor.water_leak_sensor_158d000484bff9 # Water entrance
  action:
    service: notify.telegram_tiger
    data_template:
      message: "{{ trigger.to_state.attributes.friendly_name }} is now *{{ trigger.to_state.state }}*"
