# Telegram notifications
- alias: Locks notification to telegram
  trigger:
    platform: state
    entity_id: 
      - binary_sensor.door_window_sensor_158d0003d481a6
#      - binary_sensor.door_window_sensor_158d0003d4a2b2
  action:
    service: notify.telegram_group
    data_template:
      message: "{{ trigger.to_state.attributes.friendly_name }} is now *{% if trigger.to_state.state == 'off' %}closed{% else %}open{% endif %}*"

- alias: Cookoo Chime
  trigger:
    platform: time_pattern
    minutes: 0
  condition:
    condition: time
    after: '8:00:00'
    before: '22:00:00'
  action:
    service: notify.telegram_tiger
    data_template:
      message: "*{{ now().hour }}:00*"
