- alias: Low Water Pressure
  id: low_water_pressure
  trigger:
    - platform: numeric_state
      entity_id: sensor.water_pressure_sensor_6_0
      below: 1
      for: "00:00:20" # 20s
  condition:
    - condition: state
      entity_id: switch.tank_valve
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.tank_valve
    # - service: notify.telegram_tiger
    #   data_template:
    #     message: '{{ trigger.to_state.name }} is too low: {{ trigger.to_state.state }} - turned off tank valve for a while'
    # - service: automation.turn_on
    #   entity_id: restore_tank_valve

- alias: Restore Tank Valve
  id: restore_tank_valve
  # initial_state: 'off'
  trigger:
    - platform: numeric_state
      entity_id: sensor.water_pressure_sensor_6_0
      above: 2
      for: "00:03:00" # Above 2ATM for 3m
  condition:
    - condition: state
      entity_id: switch.tank_valve
      state: 'off'
  action:
    # - service: notify.telegram_tiger
    #   data_template:
    #     message: 'Turning on tank valve'
    - service: switch.turn_on
      entity_id: switch.tank_valve
    # - service: automation.turn_off
    #   entity_id: restore_tank_valve


- alias: Morning Watering
  id: morning_watering
  trigger:
    platform: time
    at: "08:00:00"
  action:
    - service: script.morning_sprinkling

- alias: Evening Watering
  id: evening_watering
  trigger:
    platform: time
    at: "21:00:00"
  action:
    - service: script.evening_sprinkling
