# Variables
substitutions:
  plug_name: bw2
  current_res: "0.00222"
  voltage_div: "965"

esphome:
  name: bw2
  platform: ESP8266
  board: esp8285

wifi:
  ssid: "matrix_ext"
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${plug_name} Fallback"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

# Web Server  
web_server:
  port: 80  
  
binary_sensor:
  - platform: gpio
    name: ${plug_name}_button
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay

# Relay switch
switch:
  - platform: gpio
    name: ${plug_name}_relay
    pin: GPIO14
    id: relay
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - switch.turn_on: blue_led
      - switch.turn_off: red_led
    on_turn_off:
      - switch.turn_off: blue_led
      - switch.turn_on: red_led

# Blue led
  - platform: gpio
    id: blue_led
    name: ${plug_name}_led_blue
    icon: mdi:led-on
    restore_mode: ALWAYS_ON
    pin: 
      number: GPIO1
      inverted: True

# Red led
  - platform: gpio
    id: red_led
    name: ${plug_name}_led_red
    icon: mdi:led-on
    restore_mode: ALWAYS_OFF
    pin: 
      number: GPIO13
      inverted: True

# Power sensor
sensor:
  - platform: hlw8012
    sel_pin: 
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: ${plug_name}_current
      icon: mdi:current-ac
      unit_of_measurement: A
    voltage:
      name: ${plug_name}_voltage
      icon: mdi:flash-circle
      unit_of_measurement: V
    power:
      name: ${plug_name}_power
      icon: mdi:flash-outline
      unit_of_measurement: W
    initial_mode: CURRENT
    change_mode_every: 6
    update_interval: 10s

# Uptime
  - platform: uptime
    name: ${plug_name}_uptime

# WiFi Strength
  - platform: wifi_signal
    name: ${plug_name}_wifi_signal
    update_interval: 60s

# FW
text_sensor:
  - platform: version
    name: ${plug_name}_fw_version
