esphome:
  name: esp32_ble_gate3
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "matrix"
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "BLE Gate3 Fallback"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

esp32_ble_tracker:

sensor:
  - platform: xiaomi_lywsd02
    mac_address: E7:2E:00:A3:68:F7
    temperature:
      name: "Kitchen Temperature"
    humidity:
      name: "Kitchen Humidity"
      
  - platform: xiaomi_mhoc401
    mac_address: "A4:C1:38:D0:D9:42"
    bindkey: eef418daf699a0c188f3bfd17e4565d9
    temperature:
      name: "Basement Temperature"
    humidity:
      name: "Basement Humidity"
    battery_level:
      name: "Basement HT Battery Level"

  - platform: adc
    name: "Water Pressure"
    pin: GPIO35
    id: water_pressure
    update_interval: 20s
    unit_of_measurement: "bar"
    accuracy_decimals: 2
    attenuation: 11db
    filters:
      - offset: -0.48
      - multiply: 4.1
