esphome:
  name: esp_kinder1
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "matrix"
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kinder1 Fallback"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

sensor:
  - platform: dht
    pin: D2
    model: DHT22
    temperature:
      name: "Masha's Room Temperature"
    humidity:
      name: "Masha's Room Humidity"
    update_interval: 60s
