esphome:
  name: esp-zoo
  platform: ESP8266
  board: esp12e

wifi:
  ssid: "matrix"
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Zoo Fallback"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password
  
i2c:
  sda: GPIO2
  scl: GPIO0

sensor:
  - platform: bmp085
    temperature:
      name: "Zoo Temperature"
    pressure:
      name: "Atmospheric Pressure"
    update_interval: 60s  
    
  - platform: adc
    pin: A0
    name: "Zoo Brightness"
    unit_of_measurement: "lux"
    icon: "mdi:solar-power"
    update_interval: 60s
    filters:
      - lambda: "return x * 3.3 * 200;"

light:
  - platform: rgb
    name: "Zoo RGB LED"
    red: output_red
    green: output_green
    blue: output_blue

output:
# Red channel
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO15
# Green channel
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
# Blue channel
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO13
