esphome:
  name: esp_test
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "matrix"
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password
  
remote_receiver:
  pin:
    number: D1
    inverted: true
  dump:
    - nec
#  dump: all


# i2c:
#   sda: 4
#   scl: 5
#   scan: true
  
# display:
#   - platform: lcd_pcf8574
#     dimensions: 16x2
#     address: 0x27
#     lambda: |-
#       it.backlight();
#       it.printf("IP: %s", WiFi.localIP().toString().c_str());
#       it.strftime(0, 1, "%Y-%m-%d %H:%M", id(my_time).now());

# # (Optional) For displaying time:
# time:
# - platform: sntp
#   id: my_time
