esphome:
  name: esp_gym
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "matrix"
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gym Fallback"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

sensor:
  - platform: dht
    pin: D4
    model: DHT22
    temperature:
      name: "Gym Temperature"
      accuracy_decimals: 1
      id: dht_temp
    humidity:
      name: "Gym Humidity"
      accuracy_decimals: 1
      id: dht_hum
    update_interval: 60s

i2c:
  sda: 4
  scl: 5
  scan: true
  
display:
  - platform: lcd_pcf8574
    address: 0x27
    dimensions: 16x2
    lambda: |-
      it.backlight();
      it.printf("%s", WiFi.localIP().toString().c_str());
      it.printf(0, 1, "%.1f%cC, %.1f%%", id(dht_temp).state, char(223), id(dht_hum).state);
