# Variables
substitutions:
  pow_name: pow1

esphome:
  name: ${pow_name}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: "matrix"
  password: !secret wifi_password
  ap:
    ssid: ${pow_name} fallback"
    password: !secret fallback_password

captive_portal:

# Disable USB logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

# Button
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO0
      inverted: True
    name: ${pow_name}_button
    filters:
      - delayed_on: 10ms
    on_click:
      - switch.toggle: relay

# Relay and Red LED
switch:
  - platform: gpio
    name: ${pow_name}_switch
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_ON

# Blue LED
status_led:
  pin:
    number: GPIO13
    inverted: True

# Power Sensors
uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: cse7766
    update_interval: 20s
    current:
      name: ${pow_name}_current
    voltage:
      name: ${pow_name}_voltage
    power:
      name: ${pow_name}_power
