esphome:
  name: powersocket_1
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "matrix"
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password
