- platform: min_max
  type: mean
  name: "House Average Temperature"
  round_digits: 1
  entity_ids:
    - sensor.bedroom_temperature
    - sensor.masha_s_room_temperature
    - sensor.klim_s_room_temperature

- platform: min_max
  type: mean
  name: "House Average Humidity"
  round_digits: 1
  entity_ids:
    - sensor.bedroom_humidity
    - sensor.masha_s_room_humidity
    - sensor.klim_s_room_humidity

- platform: template
  sensors:
    sunrise:
      friendly_name: 'Next Sunrize Time'
      entity_id: sun.sun
      value_template: "{{ as_timestamp(state_attr('sun.sun', 'next_rising'))| timestamp_custom('%H:%M') }}"
    sunset:
      friendly_name: 'Next Sunset Time'
      entity_id: sun.sun
      value_template: "{{ as_timestamp(state_attr('sun.sun', 'next_setting'))| timestamp_custom('%H:%M') }}"
    atmospheric_pressure_mmhg:
      friendly_name: "Atmospheric Pressure"
      entity_id: sensor.atmospheric_pressure
      unit_of_measurement: mmHg
      value_template: "{{ (states('sensor.atmospheric_pressure')|float * 0.75)|round(1) }}"

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time_iso'
